### ISSUE TITLE
Error: ENOENT: no such file or directory, scandir '.coverage/instrumented/elm-stuff/generated-code/elm-community/elm-test/0.19.1-revision2'

### ISSUE THREAD

**Issue by malinoff** [zwilias/elm-coverage#26]
Hi, I'm getting the error similar to the one d594f6c fixed. I'm not sure though, where `elm-community/elm-test` is coming from - I don't have it in my test dependencies, see below.
```
$ elm-coverage --version
0.3.0
$ elm --version
0.19.1
$ elm-test --version
0.19.1
$ ls .coverage
ls: .coverage: No such file or directory
$ elm-coverage
[12:18:52.59] Instrumenting sources...
[12:18:52.76] Running tests...

elm-test 0.19.1
---------------

Running 10 tests. To reproduce these results, run: elm-test --fuzz 100 --seed 162829929476948 /Users/malinoff/Developer/opensource/elm/elm-uniform/.coverage/instrumented/tests/Tests.elm


TEST RUN PASSED

Duration: 132 ms
Passed:   10
Failed:   0

[12:18:56.85] Something went wrong:
Error: ENOENT: no such file or directory, scandir '.coverage/instrumented/elm-stuff/generated-code/elm-community/elm-test/0.19.1-revision2'
$ cat elm.json
{
    "type": "package",
    "name": "malinoff/elm-uniform",
    "summary": "Build type-safe composable, universal forms",
    "license": "GPL-3.0",
    "version": "1.0.0",
    "exposed-modules": [
        "Uniform"
    ],
    "elm-version": "0.19.0 <= v < 0.20.0",
    "dependencies": {
        "elm/core": "1.0.0 <= v < 2.0.0",
        "elm/file": "1.0.5 <= v < 2.0.0",
        "elm/time": "1.0.0 <= v < 2.0.0",
        "elm/url": "1.0.0 <= v < 2.0.0",
        "elm-community/maybe-extra": "5.0.0 <= v < 6.0.0"
    },
    "test-dependencies": {
        "elm-explorations/test": "1.0.0 <= v < 2.0.0"
    }
}
```

**Comment by jgrenat** [comment]
Installing the latest version of elm-test solved the issue for me: 

```
npm i -g elm-test
```

**Comment by malinoff** [comment]
> Installing the latest version of elm-test solved the issue for me:
> 
> ```
> npm i -g elm-test
> ```

Doesn't help.

**Comment by Evelios** [comment]
I didn't track down why this started to be a problem but I did find a solution. The elm-community was looking for extra functionality which resides in `/usr/lib/node_modules/elm-coverage/unpacked_bin` but actually resides now in `/usr/lib/node_modules/elm-coverage/bin`. I'm assuming that the directory structure within `npm` changed at some point.

I fixed this by linking to the new directory style
```sh
sudo ln -s /usr/lib/node_modules/elm-coverage/bin /usr/lib/node_modules/elm-coverage/unpacked_bin
```

**Comment by zwilias** [comment]
Note to self that people are still running into this

**Comment by j340m3** [comment]
> I didn't track down why this started to be a problem but I did find a solution. The elm-community was looking for extra functionality which resides in `/usr/lib/node_modules/elm-coverage/unpacked_bin` but actually resides now in `/usr/lib/node_modules/elm-coverage/bin`. I'm assuming that the directory structure within `npm` changed at some point.
> 
> I fixed this by linking to the new directory style
> 
> ```shell
> sudo ln -s /usr/lib/node_modules/elm-coverage/bin /usr/lib/node_modules/elm-coverage/unpacked_bin
> ```

I tried this [here](https://travis-ci.com/github/msquaredc/cookiecutted/builds/214528355#L379), but these files do not exist, so I get an error in this concern. If I didn't try to make the symbolic link, `elm-coverage` uses the `0.19.1-revision4` of  `elm-test` as seen [here](https://travis-ci.com/github/msquaredc/cookiecutted/builds/214526236#L381), but after running the tests, the it tries to find it in the folder of `0.19.1-revision2` (note the revision difference) as seen [here](https://travis-ci.com/github/msquaredc/cookiecutted/builds/214526236#L394). Also using the command line argument `--elm-test ./node_modules/.bin/elm-test` was not helping ([here](https://travis-ci.com/github/msquaredc/cookiecutted/builds/214527587#L380)).

I believe the strongest pointer to fix this is that the revision number is not matching, but I don't know enough about the internals of this library to fix it myself. Hope it is helpful for anyone :wink:

**Comment by j340m3** [comment]
Note that the `elm-test` dependency is up to date, so

> Installing the latest version of elm-test solved the issue for me:
> 
> ```
> npm i -g elm-test
> ```

didn't help either. Even worse, it's newer than what elm-coverage is looking for. I've looked through my dependencies, and the only package, where `revision2` is required is this one. Could it be that it uses any `elm-test` executable that is reachable in the first stage and uses his name to storage the results, but in the second stage it assumes that his dependency (so `revision2`) had been used and only looks there?

**Comment by jan-christiansen** [comment]
Installing the desired version of `elm-test` via 

```
npm i -g elm-test@0.19.1-revision2
```

worked for me.

**Comment by zwilias** [comment]
The last release (0.4.0) should be compatible with the current elm-test releases 👍
