### ISSUE TITLE
[Feature Request] Text result output

### ISSUE THREAD

**Issue by andys8** [zwilias/elm-coverage#9]
What a great tool. The output looks stunning!

I'm missing an argument to have a simple text based result for CI or quick commandline usage.

As an example, this is how it looks in jest:
```shell
--------------------|----------|----------|----------|----------|----------------|
File                |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
--------------------|----------|----------|----------|----------|----------------|
All files           |    60.39 |        0 |    44.44 |       62 |                |
 app                |    21.74 |        0 |        0 |    21.74 |                |
  utils.js          |    21.74 |        0 |        0 |    21.74 |... 33,35,43,50 |
 app/actions        |    67.18 |        0 |       50 |    69.29 |                |
  configurations.js |     61.9 |        0 |    41.18 |       65 |... 88,89,92,93 |
  networks.js       |      100 |      100 |      100 |      100 |                |
  profiles.js       |       60 |        0 |    43.75 |    61.36 |... 86,88,92,93 |
  templates.js      |       64 |        0 |    44.44 |    66.67 |... 43,44,47,48 |
--------------------|----------|----------|----------|----------|----------------|
```

Is this feature possible? Is it simple to implement or complicated based on the way the statistics are gathered?

**Comment by akoppela** [comment]
in the meanwhile I've implemented something similar with `gulp` task.
https://gist.github.com/akoppela/7ffe4cd2c3797a236f73be000d15e21c

**Comment by zwilias** [comment]
Current master displays something like this:

![image](https://user-images.githubusercontent.com/1038427/52964474-ac4da900-33a2-11e9-860e-dc814c49b603.png)

We can prettify it later - I think this is alright for now :)
